# Generated by Django 4.1.7 on 2023-05-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("Phone_No", models.IntegerField(default=0)),
                ("Email", models.CharField(max_length=50)),
                ("Persons", models.IntegerField(default="")),
                ("date", models.DateField()),
            ],
        ),
    ]
