# Generated by Django 4.1.7 on 2023-05-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Image", models.ImageField(upload_to="upload/images")),
                ("Menu_Name", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=0)),
            ],
        ),
    ]
