# Generated by Django 4.1.7 on 2023-05-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
